package net.cs50.finance.models;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Base class for all persistent entities.
 *
 * Created by Chris Bay on 5/18/15.
 */

// abstract class to make a unique identifier for each row in the db table
// as passed to each of its children (user, stockTransaction, StockHolding)
@MappedSuperclass
public abstract class AbstractEntity {

    private int uid;

    // hibernate annotations
    // @id = "this is a primary key"
    //   best practice is to put this on getters, not on the property
    //   (although that is legal)
    // @genval = this value is autogenerated (autoincremented) by the db
    // @col = gives properties for the db column as generated by hibernate,
    //   incl col name, which by convention is the same as the property
    //   (here, uid)
    @Id
    @GeneratedValue
    @Column(name = "uid", unique = true, nullable = false)
    public int getUid() {
        return uid;
    }

    // setter protected so that only subclasses can access it
    protected void setUid(int uid) {
        this.uid = uid;
    }

}
